### ISSUE TITLE
Arcdps URL is broken

### ISSUE THREAD

**Issue by sliekens** [gw2-addon-loader/Approved-Addons#22]
Hey, the download URL for `gw2addon_arcdps.dll` is dead. However, I was able to install it manually by downloading `d3d11.dll` from deltaconnected and renaming it myself. I think it's appropriate to change the addon manager to automate that.

![image](https://user-images.githubusercontent.com/1583241/204090497-fb50b9b5-c36b-496a-8c54-382507fcad83.png)

**Comment by Friendly0Fire** [comment]
I just confirmed that both the current download URL and the md5 hash URL still work fine.

The error you got indicates deltaconnected's server is having some issues, not that the file is gone.

**Comment by sliekens** [comment]
@Friendly0Fire nope, still broken. What URL did you use? I'm using the one from this config
https://github.com/gw2-addon-loader/Approved-Addons/blob/d0710b62e2f4183abfbce91d1d4e84511075d7e2/arcdps/update-placeholder.yaml#L23


![image](https://user-images.githubusercontent.com/1583241/204094255-e0836f1c-a1b6-491e-b581-00fa0d6a851b.png)

**Comment by sliekens** [comment]
Actually, it should be okay now, deltaconnected fixed it on their end.

![image](https://user-images.githubusercontent.com/1583241/204103847-95877dc2-ec7a-481f-9c97-c40062f7d0b1.png)
