### ISSUE TITLE
update gw2radial

### ISSUE THREAD

**Issue by ofsaleem** [gw2-addon-loader/Approved-Addons#4]
the gw2radial that the addon manager uses is about a year old now, and is missing some features. could we get an update?

**Comment by megai2** [comment]
as soon as it is out of alpha we update it 
(already in PR https://github.com/gw2-addon-loader/Approved-Addons/pull/3 )

**Comment by ofsaleem** [comment]
looks like #3 was merged and the addon manager updates to the latest gw2radial version, thanks! closing this
