### ISSUE TITLE
boontable

### ISSUE THREAD

**Issue by seanbarr1988** [gw2-addon-loader/Approved-Addons#7]
Is it possible to have a working version of the updated boon table with added colours? 

https://github.com/TvL2386/GW2-ArcDPS-Boon-Table

**Comment by megai2** [comment]
It is possible. 
Have to merge changes to our branch or use said one by default.

I'll look into this when i have free time.

**Comment by seanbarr1988** [comment]
I tried using it but it seems it needs to be made to work with addon loader as it currently wont work if you just replace the DLL

**Comment by seanbarr1988** [comment]
closing this issue as boon table is being updated for the new 1.80imgui version of arcdps and it already includes coloured table.
